name: Hola Mundo Workflow
on: [push] 

jobs:
  saludo:
    runs-on: ubunto-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Saludar
      run: echo "Hola mundo"
